spring:
  datasource:
    url: jdbc:h2:mem:appdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
    show-sql: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
